"use strict";    //*****/ treat all js code as newer version

//*****alert(3 + 3) we are using nodejs(in nodejs we use it in diff ways) not browser.
//*****engine of js is inside the browser.

let name = "siddhi" 
let age = "23"
let isLoggedIn = false

// number => 2 to the power 53
// bigint
// string => ""
// boolean => true/false
// null => standalone value(also datatype)(representaion of empty value)
// undefined => (no value added) let state; here var declared but value is not set
// symbol => find uniqueness

// OBJECT
console.log(typeof "siddhi")
console.log(typeof age);
// null is an object and undefined is undefined type
console.log(typeof null)
console.log(typeof undefined)